name: Daily Update HackerOne Src Asset

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install Requests
      run: pip install -r requirements.txt
      
    - name: Update HackerOne Src Asset
      run: python h1_asset.py
      
    - name: Commit and Push changes
      run: |
        echo $(date +'%Y%m%d') > date.txt
        git add .
        git config --local user.email "admin@adysec.com"
        git config --local user.name "adysec"
        git commit -am "$(date +'%Y%m%d')"
        git push -v --progress
